version: '3.9'

services:
  timertriggeredfunction:
    image: timertriggeredfunction
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AzureWebJobsStorage="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;"
    depends_on:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 127.0.0.1 --blobPort 10000"
    ports:
      - "10000:10000"
    
